### ISSUE TITLE
Gyroscopic stabilization of the mobile device

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#131] opened 2023-11-15 01:23 UTC
We've had our 1st user feedback - are we able to incorporate this feedback and rapidly iterate the software?

Is this a new project?

What is the scope and the cost of adding gyroscopic stabilization to the handheld?

**Comment by charlieforward9** [comment] 2023-11-15 16:59
Duplicate of VisualPT/VisualPT#6

**Closed as not planned by charlieforward9** 2023-11-15 16:59 UTC
