### ISSUE TITLE
Text Snippets: Condition Ratio

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#175] opened 2024-04-02 22:03 UTC
I’d like to be able to present text snippets that Physical Therapist you could use to help them complete their daily notes summaries. 

Even if we don’t have an LLM, could we include text snippets available for the therapist to cut and paste into their EMR?

***********

text snippets: condition ratio information (these are exclusive; only include the worst ratio in the report)

“Patient demonstrates a 33.3% ratio on the vestibular function test which puts them in the dysfunctional category.”

“Patient demonstrates a 53.3% ratio on the visual dependence test which puts them in the dysfunctional category.”

“Patient demonstrates an 83.3% ratio on the somatic sensory function test which puts them in the dysfunctional category.”

******

**Comment by charlieforward9** [comment] 2024-04-05 03:20
Duplicate of VisualPT/visualPT#161

**Closed as not planned by charlieforward9** 2024-04-05 03:20 UTC
