### ISSUE TITLE
Can the MediaPipe detect when the patient opens their eyes?

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#237] opened 2024-10-21 21:53 UTC
The PT would ordinarily judge the patient opening their eyes (in Condition #2 or Condition #5) as a 'Fall'

Can the BlazePipe do that?

![Image](https://github.com/user-attachments/assets/38b44be4-3c57-4255-a6f9-4eff5cdfeca9)

**Comment by charlieforward9** [comment] 2024-10-22 00:46
There is a face segmentation model that is embedded into the Holistic Detection which will be able to tell us if eyes are open or closed. 

Integrating this is the end goal for @DrBubbles42 Mediapipe API project

**Comment by charlieforward9** [comment] 2024-11-07 04:20
Duplicate of #210

**Closed as not planned by charlieforward9** 2024-11-07 04:20 UTC
