### ISSUE TITLE
Display on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#143] opened 2024-02-19 14:35 UTC
Right side of the iPhone display screen cuts off the Berg image icon
@charlieforward9 

![image](https://github.com/VisualPT/visualPT/assets/124405841/e2c49597-b1db-4e39-99b5-619548e66c10)

**Comment by charlieforward9** [comment] 2024-02-20 05:45
It is a horizontal scroll widget, but its clearly not too intuitive here.. I can make it a vertical scroll as I restyle the application.

I am going to close this since its not a bug and add the task to #46 to consolidate responsibilities.

**Closed as completed by charlieforward9** 2024-02-20 05:45 UTC
